Port-Group speed updates and Interface valid-speeds issue. #67
STORDIS/orca_backend pull request #42
Opened 2024-07-02 09:56 UTC by rahul-1475

If port group speed is set to 25G , all interface in the port-group are updated to have the speed 25G, but the valid speeds and adv-speed set is still 1G and 10G which is not correct.

 - The correct behaviour would be if port-group speed is updated, after receving the port-group update via gNMI subscription make an additional gnmi get to update the valid_speeds field for interface at sonic-port:sonic-port/PORT/PORT_LIST={interface_name}.

- Write test case for above.

2024-07-03 11:13 UTC, kamalkrbh commented on network/test/test_port_group.py
> +        Test port group interfaces valid speed update.
@rahul-1475 , Comment can be more verbose e.g. what use case is being tested .

2024-07-03 11:14 UTC, kamalkrbh commented on network/test/test_port_group.py
> +        port_groups = response.json()
@rahul-1475 , Unused Variable ?

2024-07-03 11:17 UTC, kamalkrbh commented on pyproject.toml
> +orca-nw-lib = "^1.3.16"
@rahul-1475, Version should be +1.
```suggestion
version = "1.3.17"
```

2024-07-03 11:26 UTC, kamalkrbh requested changes
Have a look on above comments in the files.

2024-07-04 10:50 UTC, rahul-1475 commented on network/test/test_port_group.py
> +        Test port group interfaces valid speed update.
added more doc string about the test case

2024-07-04 10:50 UTC, rahul-1475 commented on network/test/test_port_group.py
> +        port_groups = response.json()
removed unsed variables

2024-07-04 10:51 UTC, rahul-1475 commented on pyproject.toml
> +orca-nw-lib = "^1.3.16"
changed orca_nw_lib version 1.3.17

2024-07-05 04:10 UTC, kamalkrbh requested changes
@rahul-1475 , Please have a look at merge conflicts.

2024-07-05 04:56 UTC, merged